module.exports = [
  {
    name: 'ABC XYZ',
    programme: 'B.Tech (ECE)',
    mode: 'N/A',
    roll: '1901162',
    dateOfBirth: {
      day: 1,
      month: 1,
      year: 2001,
    },
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    guardiansName: 'DEF XYZ',
    permenantAddress: '10, Beltola, Guwahati, Assam. PIN-781002',
    bloodGroup: 'A+',
    emergencyContact: '6325417485',
    holdersContact: '6325417485',
    email: 'abc.xdsyz19b@iiitg.ac.in',
    admissionYear: 19,
    type: 1,
    approved: false,
    __v: 0,
  },
  {
    name: 'ABC XYZ',
    programme: 'M.Tech (CSE)',
    mode: 'on-campus',
    roll: '2102162',
    dateOfBirth: {
      day: 1,
      month: 1,
      year: 2001,
    },
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    guardiansName: 'DEF XYZ',
    permenantAddress: '10, Beltola, Guwahati, Assam. PIN-781002',
    bloodGroup: 'A+',
    emergencyContact: '6325417485',
    holdersContact: '6325417485',
    email: 'abc.xyzd21m@iiitg.ac.in',
    admissionYear: 21,
    type: 2,
    approved: false,
    __v: 0,
  },
  {
    name: 'ABC XYZ',
    programme: 'M.Tech (ECE)',
    mode: 'online',
    roll: '2102162',
    dateOfBirth: {
      day: 1,
      month: 1,
      year: 2001,
    },
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    guardiansName: 'DEF XYZ',
    permenantAddress: '10, Beltola, Guwahati, Assam. PIN-781002',
    bloodGroup: 'A+',
    emergencyContact: '6325417485',
    holdersContact: '6325417485',
    email: 'abc.xyz21m@iiitg.ac.in',
    admissionYear: 21,
    type: 2,
    approved: false,
    __v: 0,
  },
  {
    name: 'ABC XYZ',
    programme: 'PhD. (CSE)',
    mode: 'part-time',
    roll: '2103162',
    dateOfBirth: {
      day: 1,
      month: 1,
      year: 2001,
    },
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    guardiansName: 'DEF XYZ',
    permenantAddress: '10, Beltola, Guwahati, Assam. PIN-781002',
    bloodGroup: 'A+',
    emergencyContact: '6325417485',
    holdersContact: '6325417485',
    email: 'abc.xyza21m@iiitg.ac.in',
    admissionYear: 21,
    type: 3,
    approved: false,
    __v: 0,
  },
  {
    name: 'ABC XYZ',
    programme: 'PhD. (HSS)',
    mode: 'full-time',
    roll: '2103162',
    dateOfBirth: {
      day: 1,
      month: 1,
      year: 2001,
    },
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    guardiansName: 'DEF XYZ',
    permenantAddress: '10, Beltola, Guwahati, Assam. PIN-781002',
    bloodGroup: 'A+',
    emergencyContact: '6325417485',
    holdersContact: '6325417485',
    email: 'abc.xyz2g1m@iiitg.ac.in',
    admissionYear: 21,
    type: 3,
    approved: false,
    __v: 0,
  },
];
