module.exports = [
  {
    fullName: 'Shweta Sachdev',
    programme: 'B.Tech (CSE)',
    mode: 'N/A',
    roll: '1901173',
    bloodGroup: 'A+',
    dateOfBirth: {
      day: 29,
      month: 12,
      year: 2001,
    },
    guardiansName: 'Bharat Sachdev',
    emergencyContact: '9218545945',
    holdersContact: '9218545945',
    email: 'shweta.sachdev173@iiitg.ac.in',
    presentAddress: "Girls' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 19,
    type: 1,
  },
  {
    fullName: 'Ghanshyam Goswami',
    programme: 'B.Tech (CSE)',
    mode: 'N/A',
    roll: '2001163',
    bloodGroup: 'B+',
    dateOfBirth: {
      day: 22,
      month: 10,
      year: 2002,
    },
    guardiansName: 'Aadish Goswami',
    emergencyContact: '8939815614',
    holdersContact: '8939815614',
    email: 'ghanshyam.goswami163@iiitg.ac.in',
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 20,
    type: 1,
  },
  {
    fullName: 'Alka Mallick',
    programme: 'B.Tech (CSE)',
    mode: 'N/A',
    roll: '2101013',
    bloodGroup: 'AB+',
    dateOfBirth: {
      day: 15,
      month: 8,
      year: 2002,
    },
    guardiansName: 'Aadish Mallick',
    emergencyContact: '9658018727',
    holdersContact: '8939815614',
    email: 'alka.mallick013@iiitg.ac.in',
    presentAddress: "Girls' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 21,
    type: 1,
  },
  {
    fullName: 'Shweta Sachdev',
    programme: 'B.Tech (ECE)',
    mode: 'N/A',
    roll: '1901174',
    bloodGroup: 'O+',
    dateOfBirth: {
      day: 29,
      month: 12,
      year: 2001,
    },
    guardiansName: 'Bharat Sachdev',
    emergencyContact: '9218545945',
    holdersContact: '9218545945',
    email: 'shweta.sachdev174@iiitg.ac.in',
    presentAddress: "Girls' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 19,
    type: 1,
  },
  {
    fullName: 'Ghanshyam Goswami',
    programme: 'B.Tech (ECE)',
    mode: 'N/A',
    roll: '2001164',
    bloodGroup: 'B+',
    dateOfBirth: {
      day: 22,
      month: 10,
      year: 2002,
    },
    guardiansName: 'Aadish Goswami',
    emergencyContact: '8939815614',
    holdersContact: '8939815614',
    email: 'ghanshyam.goswami164@iiitg.ac.in',
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 20,
    type: 1,
  },
  {
    fullName: 'Alka Mallick',
    programme: 'B.Tech (ECE)',
    mode: 'N/A',
    roll: '2101014',
    bloodGroup: 'AB-',
    dateOfBirth: {
      day: 15,
      month: 8,
      year: 2002,
    },
    guardiansName: 'Aadish Mallick',
    emergencyContact: '9658018727',
    holdersContact: '8939815614',
    email: 'alka.mallick014@iiitg.ac.in',
    presentAddress: "Girls' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 21,
    type: 1,
  },
  {
    fullName: 'Shweta Sachdev',
    programme: 'M.Tech (CSE)',
    mode: 'online',
    roll: '1902173',
    bloodGroup: 'A+',
    dateOfBirth: {
      day: 29,
      month: 12,
      year: 2001,
    },
    guardiansName: 'Bharat Sachdev',
    emergencyContact: '9218545945',
    holdersContact: '9218545945',
    email: 'shweta.sachdev.mo173@iiitg.ac.in',
    presentAddress: "Girls' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 19,
    type: 2,
  },
  {
    fullName: 'Ghanshyam Goswami',
    programme: 'M.Tech (CSE)',
    mode: 'online',
    roll: '2002163',
    bloodGroup: 'B+',
    dateOfBirth: {
      day: 22,
      month: 10,
      year: 2002,
    },
    guardiansName: 'Aadish Goswami',
    emergencyContact: '8939815614',
    holdersContact: '8939815614',
    email: 'ghanshyam.goswami.mo163@iiitg.ac.in',
    presentAddress: "Boys' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 20,
    type: 2,
  },
  {
    fullName: 'Alka Mallick',
    programme: 'M.Tech (CSE)',
    mode: 'online',
    roll: '2102013',
    bloodGroup: 'AB+',
    dateOfBirth: {
      day: 15,
      month: 8,
      year: 2002,
    },
    guardiansName: 'Aadish Mallick',
    emergencyContact: '9658018727',
    holdersContact: '8939815614',
    email: 'alka.mallick.m013@iiitg.ac.in',
    presentAddress: "Girls' Hostel, IIIT-Guwahati, Bongora, Guwahati-781015",
    permenantAddress:
      'House No. 11/5, Tentulberia, Madhyapara, Near Natunpara Transformer, Rajpur Sonarpur(M), South 24 Parganas, Solapur, Maharashtra. PIN-413002',
    admissionYear: 21,
    type: 2,
  },
];
